version: '3.9'
services:
  redis-server:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    # restart: always
    volumes:
      - ./myredis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./myredis/data:/var/lib/redis
    command: redis-server --requirepass test-password-do-not-use-123
    networks:
      - create-and-collab-api

  mongodb:
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - create-and-collab-api

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes:
      - /mongodb-data
    networks:
      - create-and-collab-api

networks:
  create-and-collab-api:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
